### ISSUE TITLE
SavageFactions

### ISSUE THREAD

**Issue by AodX** [NoChanceSD/PvPManager-Issues#100]
Hello, i would like to report i got with PvPManager,
`[13:41:13] [Server thread/INFO]: [PvPManager] WorldGuard Found! Enabling WorldGuard Support
[13:41:13] [Server thread/ERROR]: Error occurred while enabling PvPManager v3.7.6 (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/factions/P
	at nc.bh.<init>(SourceFile:19) ~[?:?]
	at nc.bu.<init>(SourceFile:4073) ~[?:?]
	at me.NoChance.PvPManager.PvPManager.onEnable(SourceFile:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.P
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 14 more`
that i got while using SavageFactions,
can you add support to SavageFactions ?
its based on FactionsUUID, so it won't be a big problem.

**Comment by NoChanceSD** [comment]
Hello, sorry for the delay but there is SavageFactions support now. Check PvPManager v3.8.3.
