### ISSUE TITLE
Error in Spigot

### ISSUE THREAD

**Issue by jajamic** [NoChanceSD/PvPManager-Issues#104]
Hi,

I have this error when they fight do you know why please ?

[18:45:07 ERROR]: Could not pass event PlayerMoveEvent to PvPManager v3.8
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:945) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-3cb9dcb-40cbae4]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
[18:45:08 WARN]: [PvPManager] Task #89154 for PvPManager v3.8 generated an exception
java.lang.NullPointerException: null

**Comment by NoChanceSD** [comment]
Can you check if it's fixed in 3.8.1?

**Comment by NoChanceSD** [comment]
Closed for inactivity. Reopen with more information if the issue still exists.
