### ISSUE TITLE
1.12.2erro

### ISSUE THREAD

**Issue by zykool** [NoChanceSD/PvPManager-Issues#107]
[00:15:34 ERROR]: Could not pass event EntityDamageByEntityEvent to PvPManager v3.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1346) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:846) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:868) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1311) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1621) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:271) ~[%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:161) ~[%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        at me.NoChance.PvPManager.Player.TeamProfile.setInCombat(TeamProfile.java:75) ~[?:?]
        at me.NoChance.PvPManager.PvPlayer.setTagged(PvPlayer.java:148) ~[?:?]
        at me.NoChance.PvPManager.Listeners.EntityListener.onDamageActions(EntityListener.java:167) ~[?:?]
        at me.NoChance.PvPManager.Listeners.EntityListener.onPlayerDamageMonitor(EntityListener.java:103) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[%e6%96%b9%e5%9d%97%e5%b8%9d%e5%9b%bd%e7%94%9f%e5%ad%981.jar:git-Spigot-642f6d2-6103339]
        ... 26 more

**Comment by NoChanceSD** [comment]
What is the player doing when this happens?

**Comment by NoChanceSD** [comment]
Wrong repository, this is for premium version. But you could try the latest free update and see if it fixes it.
