### ISSUE TITLE
Error occurred while enabling PvPManager v3.8.8.1

### ISSUE THREAD

**Issue by Sergix7720** [NoChanceSD/PvPManager-Issues#114]
The error occurs and the plugins doesn't enable itself.

**Plugin and Server version**
Plugin version: 3.8.8.1
Server version: 1.14.4

``[00:57:25] [Server thread/ERROR]: Error occurred while enabling PvPManager v3.8.8.1 (Is it up to date?)
java.lang.NullPointerException: null
        at nc.bH.<init>(SourceFile:18) ~[?:?]
        at nc.cs.d(SourceFile:126) ~[?:?]
        at nc.cs.a(SourceFile:49) ~[?:?]
        at nc.cs.<init>(SourceFile:36) ~[?:?]
        at me.NoChance.PvPManager.PvPManager.onEnable(SourceFile:58) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot.jar:git-Spigot-56f8471-56118c6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]``

**Comment by NoChanceSD** [comment]
What's your SimpleClans version?

**Comment by Sergix7720** [comment]
I'm using the version 2.7.25
