### ISSUE TITLE
DamageEvent Bug

### ISSUE THREAD

**Issue by Serux18** [NoChanceSD/PvPManager-Issues#43]
Im using spigot 1.8.8

Config
http://pastebin.com/3FXYiXG9

[01:24:37] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to PvPManager v3.5.8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:552) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:465) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:584) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1101) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:742) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NoSuchFieldError: GLOWING
	at me.NoChance.PvPManager.PvPlayer.setTagged(SourceFile:147) ~[?:?]
	at nc.aK.c(SourceFile:2206) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor809.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6c9b0a1-de5c261]
	... 26 more

**Comment by NoChanceSD** [comment]
This should be fixed.
