### ISSUE TITLE
Task #112752 for PvPManager v3.3.2 generated an exception

### ISSUE THREAD

**Issue by andris155** [NoChanceSD/PvPManager-Issues#6]
[14:16:10] [Server thread/WARN]: [PvPManager] Task #112752 for PvPManager v3.3.2 generated an exception
java.lang.NullPointerException
	at me.NoChance.PvPManager.PvPlayer.removeCombatTeam(SourceFile:5099) ~[?:?]
	at nc.dw.run(SourceFile:137) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:780) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]

**Comment by NoChanceSD** [comment]
Do you have a nametag prefix in combat?

**Comment by NoChanceSD** [comment]
Will be fixed in next update
