### ISSUE TITLE
Disabling PvPManager v3.3.2 error server stop

### ISSUE THREAD

**Issue by andris155** [NoChanceSD/PvPManager-Issues#7]
[04:00:40] [Server thread/INFO]: [PvPManager] Disabling PvPManager v3.3.2
[04:00:40] [Server thread/ERROR]: Error occurred while disabling PvPManager v3.3.2 (Is it up to date?)
java.lang.NullPointerException
	at me.NoChance.PvPManager.PvPlayer.removeCombatTeam(SourceFile:5099) ~[?:?]
	at nc.dy.onDisable(SourceFile:58) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:454) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:650) [spigot_1.8.jar:git-PaperSpigot-5be55c3-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]

**Comment by NoChanceSD** [comment]
Similar to #6
