### ISSUE TITLE
Incompatibility with World Guard 1.13 

### ISSUE THREAD

**Issue by crazyfruit13** [NoChanceSD/PvPManager-Issues#99]
Error while trying to run PVPManager with World Guard on Spigot 13.2:
`[01:06:27] [Server thread/INFO]: [PvPManager] Enabling PvPManager v3.7.6
[01:06:27] [Server thread/INFO]: [PvPManager] Vault Found! Using it for currency related features
[01:06:27] [Server thread/ERROR]: Error occurred while enabling PvPManager v3.7.6 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionContainer()Lcom/sk89q/worldguard/bukkit/RegionContainer;
	at nc.bk.<init>(SourceFile:25) ~[?:?]
	at nc.bu.<init>(SourceFile:3060) ~[?:?]
	at me.NoChance.PvPManager.PvPManager.onEnable(SourceFile:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-e4d0c66-1057710]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-e4d0c66-1057710]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [spigot.jar:git-Spigot-e4d0c66-1057710]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [spigot.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-e4d0c66-1057710]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-e4d0c66-1057710]`

**Comment by Swede37** [comment]
I see Worldguard 7- Beta 2 is out... Maybe now it's stable enough to update?

(Crossing fingers)

**Comment by NoChanceSD** [comment]
Should be fixed on PvPManager 3.8.1
